name: firestore_api_parser
description: >-
  A Flutter and Dart plugin allowing you to convert the JSON format used by firestore REST API
  to represent its documents or collections to the conventional and usable JSON format
version: 1.1.2
repository: https://github.com/stvndelucis/firestore_api_parser

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.1
  meta: ^1.3.0
  intl: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^1.0.1
  test: ^1.24.6
